export const SITE = {
  /** Product / UI mark (matches domain styling) */
  name: "SizeToKB",
  /** SERP & meta titles — spaced for search intent */
  seoName: "Size to KB",
  domain: "sizetokb.in",
  url: "https://sizetokb.in",
  altDomain: "sizetokb.com",
  tagline: "Reduce image & signature size to exact KB · PDF & image tools",
  email: "support@sizetokb.in",
  locale: "en_IN",
  year: new Date().getFullYear(),
} as const;

/**
 * High-intent search phrases — lead with mega-volume utility terms,
 * then India exam / exact-KB intent.
 */
export const SITE_KEYWORDS = [
  // Mega-volume PDF / convert (Semrush-scale intent)
  "jpg to pdf",
  "pdf to jpg",
  "pdf to word",
  "word to pdf",
  "merge pdf",
  "compress pdf",
  "split pdf",
  "unlock pdf",
  "remove pdf password",
  "pdf to image",
  "JPG to PDF online free",
  "PDF to JPG online free",
  "PDF to Word online free",
  "Word to PDF online free",
  "merge PDF online free",
  "compress PDF online free",
  "unlock PDF online free",
  "PDF password remover",
  // Exact KB — India forms
  "reduce image size",
  "reduce image size online",
  "reduce image size in KB",
  "reduce photo size",
  "reduce photo size online free",
  "reduce photo size for form",
  "reduce signature size",
  "reduce signature size online",
  "reduce photo size to 50kb",
  "reduce photo size to 20kb",
  "reduce signature size to 20kb",
  "reduce signature size to 10kb",
  "compress image to 50kb",
  "compress image to 20kb",
  "compress image to 100kb",
  "photo size kam kaise kare",
  "signature size kam kaise kare",
  "PDF size kam kaise kare",
  "passport size photo maker",
  "passport size photo online free",
  // Exam boards
  "SSC photo size",
  "SSC signature size",
  "UPSC photo size",
  "NEET photo size",
  "JEE photo size",
  "Railway photo size",
  "IBPS photo size",
  "government exam photo resizer",
  // More tools
  "reduce PDF size online",
  "HEIC to JPG converter",
  "image to PDF converter",
  "PDF to PNG converter",
  "decrypt PDF online",
  "bulk reduce image size to KB",
  "reduce marksheet PDF size",
  "biodata maker",
  "sarkari biodata maker",
  "resume maker online free",
  "biodata format for government job",
] as const;
