export const SITE = {
  name: "SizeToKB",
  domain: "sizetokb.in",
  url: "https://sizetokb.in",
  altDomain: "sizetokb.com",
  tagline: "Reduce image & signature size to exact KB for exam forms",
  email: "support@sizetokb.in",
  locale: "en_IN",
  year: new Date().getFullYear(),
} as const;

/**
 * High-intent India search phrases (how aspirants actually type queries).
 * Used in meta keywords + on-page SEO blocks.
 */
export const SITE_KEYWORDS = [
  // Core "reduce" intent
  "reduce image size",
  "reduce image size online",
  "reduce image size in KB",
  "reduce photo size",
  "reduce photo size online free",
  "reduce photo size for form",
  "reduce signature size",
  "reduce signature size online",
  "reduce signature size in KB",
  "reduce image size for online form",
  "reduce photo size to 50kb",
  "reduce photo size to 20kb",
  "reduce signature size to 20kb",
  "reduce signature size to 10kb",
  "how to reduce image size in KB",
  "how to reduce signature size for SSC",
  "photo size kam kaise kare",
  "signature size kam kaise kare",
  "image size reduce online free",
  "photo size reduce online",
  // Compress / resize variants
  "compress image online free",
  "compress image to 50kb",
  "compress image to 20kb",
  "compress image to 100kb",
  "compress photo online",
  "compress signature online",
  "compress signature to 20kb",
  "compress signature to 10kb",
  "photo resize online free",
  "image resize online free",
  "signature resize online free",
  "resize image to 20kb",
  "resize image to 50kb",
  "resize photo to 20kb 50kb",
  "resize signature to 10kb 20kb",
  "JPG compressor online free",
  "image compressor for exam form",
  "photo size converter KB",
  "change photo size in KB",
  "decrease image size online",
  "make photo smaller KB",
  // Passport / form fill
  "passport size photo maker",
  "passport size photo online free",
  "resize photo for form fill",
  "photo for online application",
  "form photo size",
  "upload photo size limit",
  // Exam boards
  "SSC photo size",
  "SSC signature size",
  "SSC photo resize",
  "SSC CGL photo size",
  "SSC CHSL photo size",
  "SSC GD photo size",
  "SSC MTS photo size",
  "UPSC photo size",
  "UPSC signature size",
  "NEET photo size",
  "NEET signature size",
  "JEE photo size",
  "JEE Main signature size",
  "Railway photo size",
  "RRB NTPC photo size",
  "RRB Group D photo size",
  "IBPS photo size",
  "IBPS signature size",
  "SBI clerk photo size",
  "bank exam photo size",
  "government exam photo resizer",
  "sarkari form photo size",
  // Tools
  "PDF compressor online free",
  "image to PDF converter",
  "photo to PDF online",
  "image merger online free",
  "image cropper online free",
  "flip image online",
  "PDF to Word online free",
  "Word to PDF online free",
] as const;
