import type { NewsletterCategoryId, NewsletterPost, NewsletterStore } from "@/lib/newsletter";

/**
 * One helpful Q&A-style tip per tool. Written to read like real aspirant questions —
 * not keyword-stuffed doorway pages. Keep titles unique; vary exams and failure modes.
 */
type TipDraft = {
  slug: string;
  title: string;
  excerpt: string;
  body: string;
  category: NewsletterCategoryId;
  ctaLabel: string;
  ctaHref: string;
  /** Stable id so republishing does not duplicate */
  id: string;
  day: string; // YYYY-MM-DD for created/updated
};

const TIPS: TipDraft[] = [
  {
    id: "tip_compress_50kb",
    slug: "ssc-photo-20-50-kb",
    day: "2026-08-01",
    category: "exam-tips",
    title: "My SSC form says photo must be 20–50 KB. How do I make my photo that size?",
    excerpt: "Phone photos are usually 1–3 MB — here’s a calm way to hit the SSC band without ruining the face.",
    body: "Most phone cameras save photos at 1–3 MB. SSC-style forms often want something much smaller, commonly between 20 KB and 50 KB.\n\nWhat usually works:\n\n- Open the Compress to 50KB tool\n- Upload a clear front-facing photo (good light, plain background if the form asks)\n- Bring the file into the 20–50 KB range and keep it as JPG\n- Download and try the form again\n\nIf the portal still rejects it, check the notification once more — some years also mention exact width × height. Size first, then dimensions if needed.",
    ctaLabel: "Compress photo to 20–50 KB",
    ctaHref: "/compress-to-50kb/",
  },
  {
    id: "tip_compress_20kb",
    slug: "form-wants-photo-under-20kb",
    day: "2026-08-02",
    category: "size-guides",
    title: "The portal says “maximum 20 KB”. Why does my photo keep failing?",
    excerpt: "20 KB is a tight limit. A normal selfie will never pass until you compress it on purpose.",
    body: "A 20 KB cap is common on older or strict portals (sometimes for photo, sometimes for signature).\n\nYour gallery photo is fine for WhatsApp — it is not fine for that upload box. Use Compress to 20KB, upload once, and download only when the preview shows you are at or under 20 KB.\n\nTip: if the face looks too blocky after compression, start from a well-lit crop (face filling more of the frame) rather than a distant full-body shot. Less empty background usually compresses cleaner.",
    ctaLabel: "Compress to 20 KB",
    ctaHref: "/compress-to-20kb/",
  },
  {
    id: "tip_compress_100kb",
    slug: "upsc-neet-photo-around-100kb",
    day: "2026-08-03",
    category: "exam-tips",
    title: "UPSC / NEET style forms often allow up to 100 KB — how do I stay under without looking blurry?",
    excerpt: "100 KB gives more room than SSC’s 50 KB band, but a raw phone file still won’t upload.",
    body: "Many UPSC / NEET / college-style uploads allow a higher ceiling such as 100 KB. That still means you should compress — not upload the original HEIC or 4 MB JPG.\n\nUse Compress to 100KB, check the download size, and only then upload. If the form also needs a passport crop (for example 3.5 × 4.5 cm), make the crop first, then compress. Order matters: crop → compress → upload.",
    ctaLabel: "Compress to 100 KB",
    ctaHref: "/compress-to-100kb/",
  },
  {
    id: "tip_compress_10kb",
    slug: "signature-or-photo-max-10kb",
    day: "2026-08-04",
    category: "size-guides",
    title: "My form wants the file under 10 KB. Is that even possible?",
    excerpt: "Yes — usually for signatures or tiny thumb scans, not for a full colour portrait.",
    body: "A 10 KB limit almost always means signature, thumb impression, or a very small scan — not a detailed colour passport photo.\n\nUse Compress to 10KB after you have a clean crop (black ink on white paper works best). If you try to force a large colour selfie into 10 KB, it will look broken. Match the file type to what the form is asking for.",
    ctaLabel: "Compress to 10 KB",
    ctaHref: "/compress-to-10kb/",
  },
  {
    id: "tip_compress_200kb",
    slug: "document-scan-under-200kb",
    day: "2026-08-05",
    category: "form-help",
    title: "Certificate scan is 2 MB but the portal allows only 200 KB — what now?",
    excerpt: "Document uploads often use a higher KB cap than photos. Still compress before you retry.",
    body: "Marksheets and certificates photographed on a phone easily hit 2–5 MB. Portals often allow something like 200 KB for those files.\n\nCompress to 200KB is meant for that middle ground: small enough to upload, still readable if the scan is sharp. Shoot the page flat, avoid glare, then compress once. If text becomes hard to read, improve the photo first — compression cannot invent missing detail.",
    ctaLabel: "Compress to 200 KB",
    ctaHref: "/compress-to-200kb/",
  },
  {
    id: "tip_compress_500kb",
    slug: "upload-limit-500kb-for-scans",
    day: "2026-08-06",
    category: "size-guides",
    title: "Portal max is 500 KB for my PDF/photo scan. Do I still need a tool?",
    excerpt: "If your file is already under 500 KB, upload it. If not, compress once and stop.",
    body: "500 KB is generous compared with photo rules, but multi-page scans still blow past it.\n\nUse Compress to 500KB when the file is oversized. Don’t repeatedly re-compress a file that already fits — that only hurts quality. Check the file size on your phone (Details / Info) before uploading.",
    ctaLabel: "Compress to 500 KB",
    ctaHref: "/compress-to-500kb/",
  },
  {
    id: "tip_custom_kb",
    slug: "form-asks-odd-kb-range",
    day: "2026-08-07",
    category: "how-to",
    title: "My form says 30–40 KB (not 20–50). Which tool should I use?",
    excerpt: "When the notification has an unusual min–max band, use a custom KB range.",
    body: "Not every board uses the popular 20–50 KB rule. Some ask for 15–30 KB, 25–40 KB, or another band printed in the advertisement.\n\nOpen Custom reduce to KB, type the exact minimum and maximum from the form, upload, and download only when you are inside that band. Copy the numbers from the official PDF — guessing is how people get soft rejections later.",
    ctaLabel: "Custom min–max KB",
    ctaHref: "/custom/",
  },
  {
    id: "tip_image_resizer",
    slug: "which-preset-20-50-or-100kb",
    day: "2026-08-08",
    category: "how-to",
    title: "I don’t know if I need 20, 50 or 100 KB — where do I start?",
    excerpt: "Read the form once. If it lists a range, use that. If you only know “photo size”, start with the common presets.",
    body: "If the notification clearly says 20–50 KB or “max 100 KB”, follow that. If you are still unsure, open Reduce image size and try the preset that matches the exam family you are applying for (SSC-style → 50 KB path, UPSC/NEET-style → 100 KB path).\n\nAlways keep a copy of the original photo. Never overwrite your only good portrait with a compressed version.",
    ctaLabel: "Reduce image size",
    ctaHref: "/image-resizer/",
  },
  {
    id: "tip_min_kb_padder",
    slug: "file-too-small-for-upload",
    day: "2026-08-09",
    category: "form-help",
    title: "The form says my photo is “too small”. Can a file really be rejected for being under the minimum KB?",
    excerpt: "Yes — some portals enforce a minimum as well as a maximum. Padding into the band fixes that.",
    body: "People expect “too large” errors. “Too small” surprises them.\n\nIf the form wants a minimum (for example at least 20 KB) and your file is 8 KB, use Min KB padder to bring it into the allowed min–max range. Do not screenshot and re-save endlessly — that can change colour and sharpness in odd ways.",
    ctaLabel: "Fix file too small",
    ctaHref: "/min-kb-padder/",
  },
  {
    id: "tip_signature",
    slug: "signature-rejected-too-large",
    day: "2026-08-10",
    category: "exam-tips",
    title: "Bank / SSC signature upload keeps failing. How do I get it to 10–20 KB?",
    excerpt: "Sign on white paper, photo in good light, then clean and compress — don’t upload a full page scan.",
    body: "A signature should be a small crop of ink on paper, not a photo of your whole desk.\n\nUse Reduce signature size: clean the background if needed, crop tight around the signature, then download in the KB range your form lists (often around 10–20 KB).\n\nBlack pen + white paper + even light solves half the rejections before you even open a tool.",
    ctaLabel: "Reduce signature size",
    ctaHref: "/signature-cleaner/",
  },
  {
    id: "tip_exam_pack",
    slug: "need-photo-and-signature-together",
    day: "2026-08-11",
    category: "how-to",
    title: "I need both photo and signature for the same form. Can I prepare them together?",
    excerpt: "Yes — prepare both to KB, then download as a pack so you don’t mix up files at midnight.",
    body: "Most applications ask for photo and signature as separate uploads, but you can prepare them in one sitting.\n\nExam photo + sign pack lets you reduce both to the KB rules and download a ZIP. Name the files clearly (photo.jpg / sign.jpg) before you start the form so you don’t swap them under stress.",
    ctaLabel: "Exam photo + signature pack",
    ctaHref: "/exam-pack/",
  },
  {
    id: "tip_bulk",
    slug: "many-photos-same-kb-limit",
    day: "2026-08-12",
    category: "how-to",
    title: "I have to resize photos for several family members’ forms. Is there a faster way than one-by-one?",
    excerpt: "Use bulk reduce when everyone shares the same KB target, then check each face once.",
    body: "If five people all need ~50 KB photos, Bulk reduce to KB saves time: upload many images, apply the same target, download a ZIP.\n\nStill open each output once. Compression is mechanical — it will not tell you someone’s eyes are closed.",
    ctaLabel: "Bulk reduce to KB",
    ctaHref: "/bulk-reduce/",
  },
  {
    id: "tip_form_wizard",
    slug: "dont-know-exact-photo-rules",
    day: "2026-08-13",
    category: "form-help",
    title: "I lost the notification PDF. Is there a safer starting pack for common portals?",
    excerpt: "Best is always the official ad. If you only need a practical starting point, use the form wizard presets.",
    body: "Official size rules beat any blog. If you truly cannot find the PDF, Form photo wizard gives sensible starting packs used on common Indian portals — then you still verify against the form’s own message when it appears.\n\nNever invent dimensions. If the portal later shows an error with exact numbers, fix to those numbers.",
    ctaLabel: "Form photo wizard",
    ctaHref: "/form-wizard/",
  },
  {
    id: "tip_upload_fixer",
    slug: "paste-upload-error-text",
    day: "2026-08-14",
    category: "form-help",
    title: "The portal error is a long English sentence about file size. How do I turn that into an exact fix?",
    excerpt: "Paste the error into Upload error fixer — it helps map the message to a KB target.",
    body: "Errors like “File size exceeds maximum allowed limit” are vague until you know the number.\n\nUpload error fixer is for that moment: paste the message, follow the suggested KB path, then retry. Keep the original file. If the portal mentions format (JPG only), convert first, then compress.",
    ctaLabel: "Fix upload error",
    ctaHref: "/upload-fixer/",
  },
  {
    id: "tip_pan",
    slug: "pan-card-photo-size",
    day: "2026-08-15",
    category: "exam-tips",
    title: "PAN application photo is getting rejected. What size should I aim for?",
    excerpt: "Follow the PAN portal’s current help text; then reduce into a typical small-KB photo range.",
    body: "PAN photo rules can differ slightly by channel. Read the on-screen instructions for your application first.\n\nReduce PAN photo is a practical compressor for the usual small-KB portrait uploads. Use a recent photo with a clear face — old cropped wedding photos often fail quality checks even when KB is fine.",
    ctaLabel: "Reduce PAN photo",
    ctaHref: "/pan-photo/",
  },
  {
    id: "tip_aadhaar",
    slug: "aadhaar-update-photo-kb",
    day: "2026-08-16",
    category: "exam-tips",
    title: "Aadhaar update photo won’t upload. Should I compress it?",
    excerpt: "Usually yes — after you meet framing rules. UIDAI cares about quality and size together.",
    body: "For Aadhaar-related photo updates, follow the on-screen guidance for face framing and background. Then reduce the file if the upload complains about size.\n\nReduce Aadhaar photo helps with the KB step. Don’t over-compress a dark selfie — fix lighting first.",
    ctaLabel: "Reduce Aadhaar photo",
    ctaHref: "/aadhaar-photo/",
  },
  {
    id: "tip_thumb",
    slug: "thumb-impression-size-for-forms",
    day: "2026-08-17",
    category: "size-guides",
    title: "Police / bank form asks for thumb impression under 40 KB. Any tips?",
    excerpt: "Ink the thumb evenly, scan or photo on white, crop tight, then compress.",
    body: "Thumb impressions fail for two reasons: messy ink and huge file size.\n\nPress once on white paper, photograph from above without shadow, crop, then use Thumb impression to bring the file into a typical 10–40 KB band. Smudged double prints rarely pass even at the right size.",
    ctaLabel: "Thumb impression tool",
    ctaHref: "/thumb-impression/",
  },
  {
    id: "tip_pdf_compress",
    slug: "pdf-too-big-for-job-portal",
    day: "2026-08-18",
    category: "form-help",
    title: "Job portal rejects my PDF at 3 MB. How do I shrink it without killing the text?",
    excerpt: "Compress once toward the portal’s KB/MB limit. Start from a sharp scan if text looks soft.",
    body: "PDF compressor reduces file weight for exam and government uploads. Pick a target close to what the portal allows (for example a few hundred KB).\n\nIf the PDF is a phone photo of a page stuck inside a PDF wrapper, retake a flatter scan first. Compression cannot repair a blurry photo of a marksheet.",
    ctaLabel: "Compress PDF",
    ctaHref: "/pdf-compressor/",
  },
  {
    id: "tip_marksheet",
    slug: "marksheet-pdf-200-or-500kb",
    day: "2026-08-19",
    category: "size-guides",
    title: "Scholarship form wants marksheet PDF under 200 KB or 500 KB. Which preset?",
    excerpt: "Use the limit printed on the form. Prefer the higher allowed size if text must stay readable.",
    body: "Marksheet PDF shrink is built for those common 200 / 500 KB ceilings.\n\nIf both are allowed, choose the larger one when the print is small. Readable marks matter more than shaving another 50 KB.",
    ctaLabel: "Shrink marksheet PDF",
    ctaHref: "/marksheet-pdf/",
  },
  {
    id: "tip_pdf_organize",
    slug: "wrong-page-order-in-certificate-pdf",
    day: "2026-08-20",
    category: "how-to",
    title: "My merged certificate PDF has pages in the wrong order. Can I fix that before uploading?",
    excerpt: "Reorder or delete pages first, then compress if the portal still complains about size.",
    body: "Use Reorder PDF pages to fix sequence or drop blank pages. A cleaner PDF is often smaller too.\n\nAfter the pages look right, compress only if you still exceed the upload limit.",
    ctaLabel: "Reorder PDF pages",
    ctaHref: "/pdf-organize/",
  },
  {
    id: "tip_pdf_editor",
    slug: "need-to-add-note-on-pdf-before-upload",
    day: "2026-08-21",
    category: "how-to",
    title: "Can I highlight or add a short note on a PDF before I submit it?",
    excerpt: "Yes — edit in the browser, download, then check size limits again.",
    body: "Edit PDF lets you add text, highlights or simple marks privately in the browser.\n\nAfter editing, check the new file size. Annotations can increase size slightly — compress if the portal is strict.",
    ctaLabel: "Edit PDF",
    ctaHref: "/pdf-editor/",
  },
  {
    id: "tip_pdf_merge",
    slug: "combine-certificates-into-one-pdf",
    day: "2026-08-22",
    category: "how-to",
    title: "The form wants one PDF with all certificates. How do I merge them safely?",
    excerpt: "Merge in the order the form lists, then compress if the combined file is too heavy.",
    body: "Merge PDF combines separate certificate files into one. Put them in the same order as the checklist (degree, then caste, then others — whatever the form says).\n\nIf the merged file exceeds the limit, compress the result once rather than merging low-quality screenshots.",
    ctaLabel: "Merge PDF",
    ctaHref: "/pdf-merge/",
  },
  {
    id: "tip_pdf_split",
    slug: "upload-only-one-page-from-pdf",
    day: "2026-08-23",
    category: "form-help",
    title: "They only want page 1 of my marksheet PDF. How do I extract it?",
    excerpt: "Split or extract the page you need — uploading the full book often breaks size limits.",
    body: "Split PDF can pull out a page range so you upload only what the portal asked for.\n\nSmaller file, clearer review for the clerk on the other side. Win-win.",
    ctaLabel: "Split PDF",
    ctaHref: "/pdf-split/",
  },
  {
    id: "tip_jpg_pdf",
    slug: "photos-to-single-pdf-for-upload",
    day: "2026-08-24",
    category: "how-to",
    title: "I only have JPGs of my documents. How do I make one PDF for the portal?",
    excerpt: "Convert images to PDF in the right order, then shrink if needed.",
    body: "JPG to PDF is for that exact case: phone photos of pages → one PDF.\n\nOrder the images before converting. Afterward, compress if the portal has a low MB/KB cap.",
    ctaLabel: "JPG to PDF",
    ctaHref: "/image-to-pdf/",
  },
  {
    id: "tip_pdf_jpg",
    slug: "need-jpg-from-pdf-page",
    day: "2026-08-25",
    category: "how-to",
    title: "The form wants a JPG but I only have a PDF scan. What should I do?",
    excerpt: "Convert the needed page to JPG, then reduce to the photo KB rule if it is a portrait upload.",
    body: "PDF to JPG turns pages into images. If the upload is a document image, you may be done after conversion.\n\nIf it is meant to be a passport-style photo stuck inside a PDF, convert, crop the face, then compress to the photo KB rule.",
    ctaLabel: "PDF to JPG",
    ctaHref: "/pdf-to-jpg/",
  },
  {
    id: "tip_pdf_unlock",
    slug: "password-pdf-wont-upload",
    day: "2026-08-26",
    category: "form-help",
    title: "My marksheet PDF is password protected and the portal won’t accept it. Help?",
    excerpt: "Unlock it with the password you already know, download an open copy, then upload.",
    body: "Many portals silently fail on encrypted PDFs.\n\nUnlock PDF removes the password in your browser when you know the password. Then upload the unlocked file. Do not share unlocked certificates casually afterward.",
    ctaLabel: "Unlock PDF",
    ctaHref: "/pdf-unlock/",
  },
  {
    id: "tip_pdf_word",
    slug: "edit-text-from-pdf-form",
    day: "2026-08-27",
    category: "how-to",
    title: "I need editable text from a PDF notice. Can I convert it to Word?",
    excerpt: "PDF to Word works best on text PDFs — scanned photos of pages may need retyping.",
    body: "PDF to Word extracts text into a DOCX when the PDF actually contains text.\n\nIf your “PDF” is only photos of pages, conversion quality will be weak. In that case, treat it as an image workflow instead.",
    ctaLabel: "PDF to Word",
    ctaHref: "/pdf-to-word/",
  },
  {
    id: "tip_word_pdf",
    slug: "docx-to-pdf-for-portal",
    day: "2026-08-28",
    category: "how-to",
    title: "I wrote my undertaking in Word. The portal only accepts PDF — next step?",
    excerpt: "Convert DOCX to PDF, then compress if the upload limit is small.",
    body: "Word to PDF gives you a portal-friendly file. After conversion, check size. Long documents with images may still need Compress PDF.",
    ctaLabel: "Word to PDF",
    ctaHref: "/word-to-pdf/",
  },
  {
    id: "tip_passport",
    slug: "need-passport-size-35x45",
    day: "2026-08-29",
    category: "exam-tips",
    title: "Form asks for 3.5 × 4.5 cm passport photo. How do I make that from a phone selfie?",
    excerpt: "Crop to the passport ratio first, fix background if required, then reduce KB.",
    body: "Passport photo maker helps with the India 3.5 × 4.5 cm style crop (and similar sizes).\n\nDo size in centimetres/pixels first. Only after the crop looks right should you compress to the form’s KB rule. Doing KB first and cropping later often breaks the dimensions.",
    ctaLabel: "Passport photo maker",
    ctaHref: "/passport-photo/",
  },
  {
    id: "tip_white_bg",
    slug: "form-wants-white-background-photo",
    day: "2026-08-30",
    category: "exam-tips",
    title: "They want a white background but I shot the photo against a cream wall.",
    excerpt: "A plain wall is usually enough for a soft white-background pass — then compress.",
    body: "White background helps when the wall is mostly plain. Stand a little away from the wall to reduce shadows, then try White background.\n\nAfter the background looks acceptable, compress to the required KB. Fancy studio lighting is nice; a clean wall at noon is often enough for forms.",
    ctaLabel: "White background",
    ctaHref: "/white-background/",
  },
  {
    id: "tip_crop",
    slug: "face-too-small-in-frame",
    day: "2026-08-31",
    category: "how-to",
    title: "My photo was rejected because the face is too small in the frame. Fix?",
    excerpt: "Crop tighter around the head and shoulders, then hit the KB limit.",
    body: "Crop photo, keep eyes roughly in the upper half of the frame, leave a little space above the hair, then compress.\n\nA tight, well-lit crop compresses better than a full-length mirror selfie.",
    ctaLabel: "Crop photo",
    ctaHref: "/image-cropper/",
  },
  {
    id: "tip_heic",
    slug: "iphone-heic-not-accepted",
    day: "2026-09-01",
    category: "form-help",
    title: "iPhone saved HEIC and the government site only wants JPG. What do I do?",
    excerpt: "Convert HEIC → JPG first, then reduce to the form’s KB rule.",
    body: "Many Indian portals still do not understand HEIC.\n\nUse HEIC to JPG, download a JPEG, then compress with the matching KB tool. Skipping conversion is why “upload failed” happens with no useful message.",
    ctaLabel: "HEIC to JPG",
    ctaHref: "/heic-to-jpg/",
  },
  {
    id: "tip_convert",
    slug: "png-rejected-need-jpg",
    day: "2026-09-02",
    category: "form-help",
    title: "Portal says “upload JPG only” but my file is PNG. Easy fix?",
    excerpt: "Convert the format, then check KB — PNG can be larger than the same image as JPG.",
    body: "Use JPG / PNG / WebP conversion to get a JPG copy. After conversion, check whether you still exceed the size limit; compress if needed.",
    ctaLabel: "Convert image format",
    ctaHref: "/image-convert/",
  },
  {
    id: "tip_checker",
    slug: "check-kb-before-upload",
    day: "2026-09-03",
    category: "how-to",
    title: "How can I confirm width, height and KB before I touch the form?",
    excerpt: "Check the file first — guessing leads to last-minute panic.",
    body: "Check photo size shows pixels and KB so you know whether you need crop, compress, or both.\n\nThirty seconds here saves a failed submit at 11:58 pm.",
    ctaLabel: "Check photo size",
    ctaHref: "/image-checker/",
  },
  {
    id: "tip_bw",
    slug: "form-wants-black-and-white-photo",
    day: "2026-09-04",
    category: "exam-tips",
    title: "Some older forms still ask for black & white. Can I convert a colour photo?",
    excerpt: "Yes — convert to B&W, then compress to the listed KB.",
    body: "Color to B&W handles the colour step. After that, apply the same KB rule as any other photo upload.\n\nIf the form does not ask for B&W, keep colour — don’t convert “just in case”.",
    ctaLabel: "Color to B&W",
    ctaHref: "/color-bw/",
  },
  {
    id: "tip_name_date",
    slug: "name-and-date-on-exam-photo",
    day: "2026-09-05",
    category: "exam-tips",
    title: "SSC / board instructions say print name and date on the photo. How?",
    excerpt: "Stamp name + date on the image, then compress so the extra text still fits the KB cap.",
    body: "Name & date on photo adds the text the instruction booklet asks for.\n\nAdd the stamp first, then compress. If you compress first and stamp later, you may go over the KB limit again.",
    ctaLabel: "Add name & date",
    ctaHref: "/photo-name-date/",
  },
  {
    id: "tip_age",
    slug: "age-as-on-date-for-exam",
    day: "2026-09-06",
    category: "exam-tips",
    title: "How do I calculate age “as on” the cut-off date in the notification?",
    excerpt: "Use the official cut-off date from the PDF — not today’s date.",
    body: "Age as on date is for eligibility math. Enter your DOB and the cut-off printed in the advertisement.\n\nIf two dates appear (application vs exam), use the one the age paragraph names. Wrong age bands cause application rejection even when photos are perfect.",
    ctaLabel: "Age as on date",
    ctaHref: "/age-calculator/",
  },
  {
    id: "tip_biodata",
    slug: "sarkari-biodata-with-photo",
    day: "2026-09-07",
    category: "how-to",
    title: "I need a simple sarkari-style biodata PDF with photo. Where do I start?",
    excerpt: "Fill a clean biodata, attach a properly sized photo, download PDF.",
    body: "Biodata / resume maker is for print-ready biodata when a job or interview asks for it.\n\nPrepare the photo to KB separately if the biodata will also be uploaded online later.",
    ctaLabel: "Biodata maker",
    ctaHref: "/biodata/",
  },
  {
    id: "tip_id_masker",
    slug: "blur-aadhaar-before-sharing",
    day: "2026-09-08",
    category: "updates",
    title: "Someone asked me to WhatsApp my Aadhaar photo. Should I mask the numbers first?",
    excerpt: "Yes — blur ID numbers before you share, even with people you trust.",
    body: "Mask ID numbers softens Aadhaar / ID digits on a photo before sharing.\n\nForms that officially require a full unmasked scan are different — follow those instructions. Casual sharing is where masking matters.",
    ctaLabel: "Mask ID numbers",
    ctaHref: "/id-masker/",
  },
  {
    id: "tip_flip",
    slug: "photo-uploaded-upside-down",
    day: "2026-09-09",
    category: "form-help",
    title: "My uploaded photo shows sideways on the preview. Can I rotate it first?",
    excerpt: "Rotate or flip locally, download, then upload again.",
    body: "Flip / rotate fixes orientation before the portal locks it in.\n\nAfter rotating, re-check KB — some saves change file size slightly.",
    ctaLabel: "Flip / rotate",
    ctaHref: "/image-reverse/",
  },
  {
    id: "tip_merge_images",
    slug: "join-two-photos-one-file",
    day: "2026-09-10",
    category: "how-to",
    title: "Rare case: form wants photo and signature in one image side by side. How?",
    excerpt: "Merge the two images, then compress the combined file to the stated KB.",
    body: "Most forms want separate uploads. When a rare portal wants one combined image, Merge images can place them side by side.\n\nThen compress the result. Prefer separate uploads whenever the form allows it — cleaner reviews.",
    ctaLabel: "Merge images",
    ctaHref: "/image-merger/",
  },
  {
    id: "tip_photo_guide",
    slug: "photo-looks-ok-still-rejected",
    day: "2026-09-11",
    category: "form-help",
    title: "KB is correct but the photo still fails “quality” checks. What else should I look at?",
    excerpt: "Brightness, blur and framing fail as often as file size.",
    body: "Photo guidelines check is a quick pass for blur, framing and brightness before you obsess over another KB tweak.\n\nA sharp, well-lit 45 KB photo beats a dark 20 KB photo every time.",
    ctaLabel: "Photo guidelines check",
    ctaHref: "/photo-guide/",
  },
  {
    id: "tip_size_hindi",
    slug: "photo-size-kam-kaise-kare",
    day: "2026-09-12",
    category: "how-to",
    title: "Photo size kam kaise kare — seedha steps kya hain?",
    excerpt: "Pehle official KB limit padho, phir compress karo, last mein form pe try karo.",
    body: "Sabse pehle notification mein photo size (KB) dekho. Uske baad Size to KB pe us limit ke hisaab se compress karo aur JPG download lo.\n\nDetail steps Hindi guide pe hain — wahan se matching tool khol sakte ho.",
    ctaLabel: "Size kam kaise kare",
    ctaHref: "/size-kam-kaise-kare/",
  },
  {
    id: "tip_sign_hindi",
    slug: "signature-size-kam-kaise-kare",
    day: "2026-09-13",
    category: "how-to",
    title: "Signature size kam kaise kare jab form 10–20 KB maange?",
    excerpt: "Safed paper, black pen, tight crop, phir compress.",
    body: "Signature ko full page scan mat banao. Crop karke Signature cleaner / Hindi guide follow karo aur 10–20 KB band mein lao.\n\nAgar background gila ya peela hai to pehle clean karo, size baad mein.",
    ctaLabel: "Signature size kam kare",
    ctaHref: "/signature-size-kam-kaise-kare/",
  },
  {
    id: "tip_pdf_hindi",
    slug: "pdf-size-kam-kaise-kare",
    day: "2026-09-14",
    category: "how-to",
    title: "PDF size kam kaise kare jab marksheet upload reject ho?",
    excerpt: "Pehle pages saaf rakho, phir compress — blurry photo-PDF ko bar-bar squeeze mat karo.",
    body: "Agar PDF phone photo se bani hai to pehle better scan lo. Uske baad PDF compressor / Hindi guide se size kam karo.\n\nPortal ki limit (100/200/500 KB) notification se copy karo.",
    ctaLabel: "PDF size kam kare",
    ctaHref: "/pdf-size-kam-kaise-kare/",
  },
  {
    id: "tip_watermark",
    slug: "stamp-for-upload-only",
    day: "2026-09-15",
    category: "updates",
    title: "Should I watermark a document “FOR UPLOAD ONLY” before emailing it?",
    excerpt: "Useful when sharing a copy outside the official portal — not a substitute for size rules.",
    body: "Watermark FOR UPLOAD can mark a file before you share it casually.\n\nIt does not replace KB limits. Size the file for the portal separately; watermark when you want a visible “this is a copy” stamp.",
    ctaLabel: "Watermark tool",
    ctaHref: "/watermark/",
  },
];

export function buildToolNewsletterStore(): NewsletterStore {
  const posts: NewsletterPost[] = TIPS.map((t) => {
    const iso = `${t.day}T10:00:00.000Z`;
    return {
      id: t.id,
      slug: t.slug,
      title: t.title,
      excerpt: t.excerpt,
      body: t.body,
      category: t.category,
      published: true,
      ctaLabel: t.ctaLabel,
      ctaHref: t.ctaHref,
      createdAt: iso,
      updatedAt: iso,
    };
  });
  return {
    version: 1,
    updatedAt: new Date().toISOString(),
    posts,
  };
}

export function toolTipCount() {
  return TIPS.length;
}
